[Variables]

; --------------------General--------------------

;default=8,8,15
MainColor=3,4,8

;default=3,90,200
SecondColor=11,64,138

;default=170,170,170
ThirdColor=199,199,199

;default=200
Transparency=2

Transparent=0,0,0,0

;default=Source Code Pro
Font=Source Code Pro

FontSizeXXL=40
FontSizeXL=30
FontSizeL=20
FontSizeM=15
FontSizeS=10

; --------------------Settings--------------------

;default=355
S_Height=355

;default=500
S_Width=500

; --------------------Drives--------------------

;default=C:
Drive1=C:

;default=D:
Drive2=D:

;default=S:
Drive3=S:

; --------------------Visualizer--------------------

;default=0
FlipVisualizer=0

;default=1
Hidden=1

;default=50
BarCount=73

;default=1
BarMinHeight=2

;default=200
BarHeight=300

;default=20
BarWidth=20

;default=10
BarGap=15

;default=0
BarRadius=2

;default=8,8,15
VisualizerColor=235,229,129

;default=200
VisualizerTransparency=220

; --------------------Weather--------------------

;Find your location code: https://weather.com/. The code will be in the URL, as example: https://weather.com/weather/today/l/[LOCATION]:4:US
Location=SZXX0006

;Fahrenheit = "TempUnit=F"
;Celcius = "TempUnit=M"
TempUnit=M

; --------------------Cutout--------------------

;Place cutout in here: @Resources\Cutout
Cutout=Cutout_Nature.png
