[MeterBar0]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth0]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar1]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth1]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar2]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth2]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar3]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth3]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar4]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth4]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar5]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth5]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar6]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth6]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar7]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth7]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar8]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth8]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar9]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth9]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar10]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth10]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar11]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth11]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar12]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth12]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar13]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth13]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar14]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth14]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar15]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth15]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar16]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth16]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar17]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth17]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar18]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth18]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar19]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth19]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar20]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth20]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar21]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth21]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar22]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth22]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar23]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth23]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar24]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth24]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar25]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth25]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar26]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth26]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar27]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth27]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar28]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth28]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar29]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth29]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar30]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth30]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar31]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth31]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar32]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth32]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar33]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth33]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar34]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth34]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar35]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth35]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar36]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth36]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar37]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth37]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar38]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth38]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar39]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth39]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar40]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth40]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar41]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth41]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar42]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth42]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar43]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth43]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar44]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth44]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar45]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth45]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar46]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth46]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar47]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth47]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar48]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth48]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar49]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth49]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar50]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth50]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar51]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth51]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar52]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth52]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar53]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth53]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar54]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth54]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar55]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth55]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar56]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth56]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar57]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth57]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar58]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth58]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar59]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth59]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar60]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth60]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar61]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth61]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar62]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth62]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar63]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth63]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar64]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth64]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar65]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth65]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar66]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth66]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar67]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth67]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar68]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth68]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar69]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth69]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar70]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth70]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar71]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth71]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1

[MeterBar72]
Meter=Shape
X=15R
Y=300
Shape=Rectangle 0,0,20,(-300*[MeasureBandSmooth72]),2 | Fill Color 235,229,129,220 | StrokeWidth 0
DynamicVariables=1
