[Variables]

; --------------------Weather--------------------

WeatherSub="Mostly":"Meist","Partly":"Teils","AM":"Morgens","PM":"Nachmittags","Light":"Leichter","Heavy":"Starker","Patches of Fog":"Nebelschwaden","T-Storms":"Gewitter","Thunder":"Gewitter","to":"bis","Sunny":"Sonnig","Cloudy":"Bewölkt","Fair":"Schön","Sun":"Sonne","Rain":"Regen","Drizzle":"Nieselregen","Freezing":"Frostiger","Isolated":"Isolierte","Ice":"Eis","Wintry Mix":"Schneeregen","Snow":"Schnee","Clouds":"Wolken","Fog":"Nebel","Mist":"Nebel","Showers":"Schauer","Shower":"Schauer","in the Vicinity":"in der Umgebung"
WeatherDaysSub="Mon":"MO","Tue":"DI","Wed":"MI","Thu":"DO","Fri":"FR","Sat":"SA","Sun":"SO"

; --------------------Settings--------------------
; -----All-----
Title=Einstellungen
LabelGeneral=Generell
LabelDrives=Laufwerke
LabelVisualizer=Visualizer
LabelWeather=Wetter

; -----General-----
LabelMainColor=Hauptfarbe
LabelSecondColor=Zweitfarbe
LabelThirdColor=Drittfarbe
LabelTransparency=Transparenz
LabelCutout=Ausschnitt
LabelLanguage=Sprache

; -----Drives-----
LabelDrive=Laufwerk

; -----Visualizer-----
LabelFlip=Visualizer umdrehen
LabelBarCount=Balkenanzahl
LabelBarHeight=Balkenhöhe
LabelBarWidth=Balkenbreite
LabelBarMinHeight=Balkenmindesthöhe
LabelBarGap=Balkenlücke
LabelBarRadius=Balkenradius
LabelColor=Farbe

; -----Weather-----
LabelLocation=Standort
LabelTempUnit=Temperatureinheit

; --------------------Search--------------------
; -----Google&Youtube-----
LabelAll=Alle
LabelVideos=Videos

; -----Google-----
LabelImages=Bilder
LabelShopping=Shopping

; -----Youtube-----
LabelChannels=Kanäle
LabelPlaylists=Playlists

; -----Stackoverflow-----
LabelRelevance=Relevanz
LabelNewest=Neuste
